// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DumpFile(arg1, arg2) {
  return window['go']['lib']['Restoric']['DumpFile'](arg1, arg2);
}

export function DumpFileToTemp(arg1, arg2) {
  return window['go']['lib']['Restoric']['DumpFileToTemp'](arg1, arg2);
}

export function GetFilesForPath(arg1, arg2) {
  return window['go']['lib']['Restoric']['GetFilesForPath'](arg1, arg2);
}

export function OpenFileOrUrl(arg1) {
  return window['go']['lib']['Restoric']['OpenFileOrUrl'](arg1);
}

export function OpenRepo(arg1, arg2) {
  return window['go']['lib']['Restoric']['OpenRepo'](arg1, arg2);
}

export function RestoreFile(arg1, arg2) {
  return window['go']['lib']['Restoric']['RestoreFile'](arg1, arg2);
}

export function SelectRepo() {
  return window['go']['lib']['Restoric']['SelectRepo']();
}
