// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenRepo(arg1, arg2) {
  return window['go']['lib']['Restoric']['OpenRepo'](arg1, arg2);
}

export function SelectRepo() {
  return window['go']['lib']['Restoric']['SelectRepo']();
}

export function GetFilesForSnapshot(arg1) {
  return window['go']['lib']['Restoric']['GetFilesForSnapshot'](arg1);
}

export function Greet(arg1) {
  return window['go']['lib']['Restoric']['Greet'](arg1);
}
