// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilesForPath(arg1, arg2) {
  return window['go']['lib']['Restoric']['GetFilesForPath'](arg1, arg2);
}

export function OpenRepo(arg1, arg2) {
  return window['go']['lib']['Restoric']['OpenRepo'](arg1, arg2);
}

export function SelectRepo() {
  return window['go']['lib']['Restoric']['SelectRepo']();
}
