// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function GetFilesForSnapshot(arg1:string):Promise<lib.VuetifyTreeNode|Error>;

export function Greet(arg1:string):Promise<string>;

export function OpenRepo(arg1:string,arg2:string):Promise<Array<lib.Snapshot>|Error>;

export function SelectRepo():Promise<string|Error>;
