// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function GetFilesForPath(arg1:string,arg2:string):Promise<Array<lib.File>|Error>;

export function OpenRepo(arg1:string,arg2:string):Promise<Array<lib.Snapshot>|Error>;

export function SelectRepo():Promise<string|Error>;
