// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restic} from '../models';

export function SelectLocalRepo():Promise<string|Error>;

export function DumpFile(arg1:string,arg2:restic.File):Promise<string|Error>;

export function DumpFileToTemp(arg1:string,arg2:restic.File):Promise<string|Error>;

export function GetFilesForPath(arg1:string,arg2:string):Promise<Array<restic.File>|Error>;

export function OpenFileOrUrl(arg1:string):Promise<Error>;

export function OpenRepo(arg1:restic.Location,arg2:string):Promise<Array<restic.Snapshot>|Error>;

export function RestoreFile(arg1:string,arg2:restic.File):Promise<string|Error>;
