// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function DumpFile(arg1:string,arg2:lib.File):Promise<string|Error>;

export function DumpFileToTemp(arg1:string,arg2:lib.File):Promise<string|Error>;

export function GetFilesForPath(arg1:string,arg2:string):Promise<Array<lib.File>|Error>;

export function OpenFileOrUrl(arg1:string):Promise<Error>;

export function OpenRepo(arg1:string,arg2:string):Promise<Array<lib.Snapshot>|Error>;

export function RestoreFile(arg1:string,arg2:lib.File):Promise<string|Error>;

export function SelectRepo():Promise<string|Error>;
