// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectLocalRepo() {
  return window['go']['lib']['ResticBrowserApp']['SelectLocalRepo']();
}

export function DumpFile(arg1, arg2) {
  return window['go']['lib']['ResticBrowserApp']['DumpFile'](arg1, arg2);
}

export function DumpFileToTemp(arg1, arg2) {
  return window['go']['lib']['ResticBrowserApp']['DumpFileToTemp'](arg1, arg2);
}

export function GetFilesForPath(arg1, arg2) {
  return window['go']['lib']['ResticBrowserApp']['GetFilesForPath'](arg1, arg2);
}

export function OpenFileOrUrl(arg1) {
  return window['go']['lib']['ResticBrowserApp']['OpenFileOrUrl'](arg1);
}

export function OpenRepo(arg1, arg2) {
  return window['go']['lib']['ResticBrowserApp']['OpenRepo'](arg1, arg2);
}

export function RestoreFile(arg1, arg2) {
  return window['go']['lib']['ResticBrowserApp']['RestoreFile'](arg1, arg2);
}
