// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restic} from '../models';

export function DefaultRepoLocation():Promise<restic.Location>;

export function DumpFile(arg1:string,arg2:restic.File):Promise<string>;

export function DumpFileToTemp(arg1:string,arg2:restic.File):Promise<string>;

export function GetFilesForPath(arg1:string,arg2:string):Promise<Array<restic.File>>;

export function OpenFileOrUrl(arg1:string):Promise<void>;

export function OpenRepo(arg1:restic.Location):Promise<Array<restic.Snapshot>>;

export function ReadPasswordFromFile():Promise<string>;

export function RestoreFile(arg1:string,arg2:restic.File):Promise<string>;

export function SelectLocalRepo():Promise<string>;
