// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultRepoLocation() {
  return window['go']['main']['ResticBrowserApp']['DefaultRepoLocation']();
}

export function DumpFile(arg1, arg2) {
  return window['go']['main']['ResticBrowserApp']['DumpFile'](arg1, arg2);
}

export function DumpFileToTemp(arg1, arg2) {
  return window['go']['main']['ResticBrowserApp']['DumpFileToTemp'](arg1, arg2);
}

export function GetFilesForPath(arg1, arg2) {
  return window['go']['main']['ResticBrowserApp']['GetFilesForPath'](arg1, arg2);
}

export function OpenFileOrUrl(arg1) {
  return window['go']['main']['ResticBrowserApp']['OpenFileOrUrl'](arg1);
}

export function OpenRepo(arg1) {
  return window['go']['main']['ResticBrowserApp']['OpenRepo'](arg1);
}

export function ReadPasswordFromFile() {
  return window['go']['main']['ResticBrowserApp']['ReadPasswordFromFile']();
}

export function RestoreFile(arg1, arg2) {
  return window['go']['main']['ResticBrowserApp']['RestoreFile'](arg1, arg2);
}

export function SelectLocalRepo() {
  return window['go']['main']['ResticBrowserApp']['SelectLocalRepo']();
}
